import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.evaluate(() => window.scrollTo(0, 2100));
await page.waitForTimeout(300);
const box = await page.locator(".marquee-track").first().boundingBox();
const before = await page.evaluate(() => getComputedStyle(document.querySelector(".marquee-track")).animationPlayState);
await page.mouse.move(box.x + 100, box.y + box.height / 2, { steps: 5 });
await page.waitForTimeout(200);
const after = await page.evaluate(() => getComputedStyle(document.querySelector(".marquee-track")).animationPlayState);
console.log("before:", before, "after hover:", after);
await browser.close();
